language: c
sudo: false
compiler:
  - clang
  - gcc
script:
  - git clone https://github.com/andschwa/c-unit-test.git test
  - gcc -O -Wall -Werror -std=gnu99 -DTEST_DEBUG -DLIST_DEBUG -o test_list list.c test_list.c test/test.c
  - ./test_list
